# Fuel Dashboard Documentation Site
title: Fuel Dashboard
description: GSM Sites Fueling Plan Management
author: GSM Team
theme: jekyll-theme-primer
baseurl: /fuel-Dashboard

# Jekyll Build Settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Site Settings
logo: /assets/images/logo.svg

# Collections and defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude these files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
